### PR TITLE
Replace existing exhibits in the chain when they are already there

### LINKED ISSUE #55: Explicit exhibit loading is incompatible with rails' autoreload
I've been experiencing a problem with autoreloading of exhibits. Any time I update the code in an exhibit I have to restart my server to get the new code. I've done some digging and found that this is specific to the `explicit` configuration option. When I use, e.g.

    DisplayCase.configure do |config|
      config.explicit = true
      config.exhibits = [
        OneExhibit,
        TwoExhibit
      ]
    end

then autoreloading stops working. If I comment out the `config.explicit` option (which causes the `config.exhibits` option to be ignored) then autoreloading works. I've tried this in Rails 3.2 and 4.1. I've also tried this with Ruby 1.9.3 and Ruby 2.2. All environments are consistent in this behavior.

I have an example, base application here: https://github.com/pdobb/display_case_reexhibit_test_app-rails_3.2

To recreate the issue just clone the repo and:
1. `bundle install` (currently setup for Ruby 1.9.3... if using Ruby 2 change the `pry-debugger` gem to `pry-byebug` ... or just comment out.)
2. `rails s`
3. Visit: [http://localhost:3000](http://localhost:3000)
4. Reload
5. Open app/exhibits/one_exhibit.rb and add an invalid expression to the top of OneExhibit#do_render_with_self1
6. Reload

You will notice the exception does not trip until restarting the server and reloading the page. But, if you remove the explicit exhibit loading in config/initializers/display_case.rb and repeat the above autoreloading will work as expected.

I plan to try digging into the gem and see if I can figure out what's going on here... but may need help.

Thanks!

### PR DESCRIPTION
**Pull request by codeodor**
Fixes #55

@pdobb do you want to give this branch a try to see if it fixes the issue in your real app?

Thanks,
Sam

### CODE REVIEW

**Comment by pdobb** [comment]
@codeodor this works for simple exhibits (even ones that are namespace; see below). I can make changes, reload, change back, reload and all is good. But it still doesn't seem to work properly with exhibits that are involved in inheritance.

First, it may be useful to know that my test models are namespaced. So my exhibits look something like this:

    module Ctd
      class SuperclassExhibit
      end
    end

    module Ctd
      class SubclassExhibit < Ctd::SuperclassExhibit
      end
    end

In my initial testing:
- Editing Ctd::Superclass exhibit doesn't seem to autoreload at all -- the change isn't picked up. 

- Editing Ctd::Subclass exhibit goes something like this:

1) Edit Ctd::SubclassExhibit to contain an undefined method 'asdf'
2) Ctd::SublcassExhibit picks up the change and reports: undefined local variable or method `asdf' for Ctd::SublcassExhibit
3) Edit Ctd::SublcassExhibit to remove the undefined method 'asdf'
4) Reload, get: Uninitialized constant SubclassExhibit (note: no 'Ctd' namespace is referenced)
5) Reload, get: undefined local variable or method 'asdf' for Ctd::SublcassExhibit (even though it was previously removed)

Each reload from here repeats the error in 5 each time. Restarting the server clears it up again.

**Comment by codeodor** [comment]
Oh, I think I "get" the inheritance problem now.

Any chance you could add a test case to this that demonstrates it?

**Comment by codeodor** [comment]
Also thanks for the detailed report! :+1:

**Comment by pdobb** [comment]
Yes, I will give that a go just as soon as I get some time. Probably not
until next week. Thanks!

**Comment by codeodor** [comment]
>UPDATE: The holiday season has made spare time a precious commodity of late. It may be a few weeks before I can get back to this at this point. But I will get to it!

Tell me about it! :smile:   I was thinking I'd get to it soon but I feel you there.

**Comment by codeodor** [comment]
@pdobb I finally had some time to come back to this, but I could not reproduce after this patch was in place.

However, I was trying it out not namespaced, and just reviewing your post again, I see that might be the issue. So let me try that now.

**Pull request merged**
