### PR TITLE
Remove the exhibit and retry if loading it resulted in a TypeError

### LINKED ISSUE #50: superclass mismatch error
This is very similar to #13. I have several exhibits, and one exhibit I am actually inheriting from another exhibit which causes a `TypeError: superclass mismatch for class Blah2Exhibit`.

I've updated the display_case test app @codeodor originally tested in #13 to reflect what I have and to show the error I'm getting, that can be found here: [tielur/display_case_test_rails_app](https://github.com/tielur/display_case_test_rails_app)
Here's an example of `rails console` when I use `reload!` inside of pry.

Any advice?

```
rails c
Loading development environment (Rails 3.2.5)
2.1.2 :001 > reload!
Reloading...
TypeError: superclass mismatch for class Blah2Exhibit
    from /Users/tclemens/sites/display_case_test_rails_app/app/exhibits/blah2_exhibit.rb:1:in `<top (required)>'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:11:in `block (2 levels) in find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:10:in `each'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:10:in `block in find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:6:in `each'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:6:in `find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/railtie.rb:6:in `block in <class:Railtie>'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:429:in `_run__70228025375963374__prepare__1546765089173593693__callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/actionpack-3.2.5/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/actionpack-3.2.5/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/console/app.rb:32:in `reload!'
    from (irb):1
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands/console.rb:47:in `start'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands/console.rb:8:in `start'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'2.1.2 :002 > 
```

### PR DESCRIPTION
**Pull request by codeodor**
(re)Fixes #50, hopefully for good!

I would appreciate comments on this. I don't like it, but is it acceptable, given the alternative (which is to force restarts)?

@avdi @hlcfan @tielur @mattvanhorn @jredville @amaierhofer @AlexParamonov I included you all since you participated in similar issues or pull requests.

### CODE REVIEW

**Comment by hlcfan** [comment]
For development, it's nice to `catch` these errors, I think it's good to go.

**Comment by hlcfan** [comment]
Where're we on this PR?

**Comment by codeodor** [comment]
I was hoping for some more feedback. I plan to merge it and deploy a new version of the gem this weekend unless there is some objection to the methods employed.

I've always wanted to put ¯\_(ツ)_/¯ in a commit message, so I'll probably rebase and force push before merging to master. :grinning:

**Comment by jredville** [comment]
Is there any chance we can make this only apply in non-production, or does the code path leading to this only happen in non-prod environments?

**Comment by mattr-** [comment]
Just No. Please don't do this. You will commonly see this in codebases where there's exhibit inheritance going on, such as

```ruby
class FooExhibitBase < DisplayCase::Exhibit
end

class BarExhibit < FooExhibitBase
end
```

IMHO, using inheritance with exhibits is an anti-pattern due to the fact that they're decorators. People should be fixing their codebases to not use inheritance with exhibits instead of forcing this into DisplayCase.

**Comment by mattr-** [comment]
Also, this is only a problem in development environments since production environments will never be doing automatic code reloading and is another reason that I strongly object to this change landing in DisplayCase itself.

**Comment by codeodor** [comment]
@jredville In default setting this should not be reachable via production in Rails. However, I can't promise someone hasn't turned on development-like features like autoloading changes in production. But if they had turned it on, wouldn't they still want this to happen?

@mattr- Outside of exhibit anti-patterns, is there a reason not to do this?

This issue has come up a lot. I love working on DisplayCase from time to time, but I don't love spending a lot of time trying to fix a new issue that comes in, only to realize later that it's the same issue I've dealt with multiple times in the past. 

If this code comes in, I won't have to deal with this issue again. For that reason, I'm strongly for it.

I'm also for improving the developer experience in development mode. Strongly for it.

My main concern is: does this have any unintended consequences I'm not thinking of?

**Comment by codeodor** [comment]
@mattr- if we added a check for `if Rails.env.development?` would that alleviate your concern?

**Comment by mattr-** [comment]
Adding a check for `Rails.env.development` doesn't really address my concern because development is the only environment we (being @hlcfan and I) currently see this error in our app. I'd rather see a blurb in the README about how exhibit inheritance isn't supported by DisplayCase. I think that's a valid compromise. I understand your concerns about having to deal with a repeat issue over and over but the whole reason Ruby throws an exception about superclass mismatches is because somebody is trying to do something bad. Since this isn't DisplayCase's fault, I don't see why the gem should be handling it.

**Comment by codeodor** [comment]
In general I agree with that assessment, but I think this *is* DisplayCase's fault, given the way we're messing with delegation and changing its responses to inquiries about what type of object it is.

Exhibit (omg I couldn't help myself) A: https://github.com/objects-on-rails/display-case/blob/master/lib/display_case/exhibit.rb#L118-L134

Consider: 

1. DisplayCase is doing the bad stuff Ruby is trying to warn us about.

2. We check if the class we're trying to overwrite is an `Exhibit` before re-defining the constant

3. Only DisplayCase loads Exhibits via this method, so coupled with 3, we should be isolated and sure that it's OK to redefine it.

I don't see a way that DisplayCase would be ignore a legitimate superclass mismatch because if the class was not an Exhibit, this would not apply. And if it was an Exhibit, they would want this.

... Well, I guess unless someone has loaded a dependency that defines ExhibitA and their app defines it too.

:weary: 

Maybe as a config option with a note in the readme like you mentioned? But at least a way for people to help themselves?

**Comment by codeodor** [comment]
I seem to remember someone once saying if they used `DisplayCase.configuration.explicit?` that this problem went away. If that's the case, and I guess I'll have to test it out when I have time, maybe if we freeze the exhibit chain it would help. But then, will that work in the case someone adds a new exhibit rather than updating an existing one?

**Comment by mattr-** [comment]
I'd happily support a config option with a note in the README. That's an excellent idea!

**Comment by codeodor** [comment]
Ok, thanks for the feedback. See, it helped me prevent another type of bug coming through. :smile: 

Anyone else notice anything I should keep a look out for?

**Comment by codeodor** [comment]
Released version 0.2.0 on rubygems.org

**Pull request merged**
